### ISSUE TITLE
Error while testing "import network"

### ISSUE THREAD

**Issue by alexcotoranu** [agoose77/PyAuthServer#5] opened 2015-05-11 01:55 UTC
Hi I'm experiencing the following issue:

![image](https://cloud.githubusercontent.com/assets/12387209/7557413/fc642588-f745-11e4-9e56-e7aca217f9da.png)

Windows 8.1

**Comment by agoose77** [comment] 2015-05-22 21:22
Hi Alex, sorry for the late reply - I wasn't notified.
This library is designed for Python 3, which is probably the cause of your error :)

**Comment by agoose77** [comment] 2015-06-20 13:13
As error was due to user, closing :)

**Closed as completed by agoose77** 2015-06-20 13:13 UTC

**Comment by alexcotoranu** [comment] 2015-08-19 23:48
Hi, sorry about my late reply. I haven't had a chance to try this out again for some time :(

In any case, if I am not mistaken I tried this with Python 3 first, and experienced the same issue. I'll have another crack at it soon. In any caes you're probably right in the fact that it's likely a user error :)
